name: emarket

version: '3.8'

services:
  # 1. Отдельный контейнер БД для Catalog Service
  catalog-postgres:
    image: postgres:16-alpine
    container_name: catalog-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432" # Внешний порт 5433 перенаправляется на внутренний 5432
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  # 2. Отдельный контейнер БД для Order Service
  order-postgres:
    image: postgres:16-alpine
    container_name: order-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5434:5432" # Внешний порт 5434 перенаправляется на внутренний 5432
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  # 3. Брокер сообщений RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: microservices-rabbitmq
    ports:
      - "5672:5672"   # Порт для MassTransit
      - "15672:15672" # Порт для веб-панели управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservice-network

# Объявляем отдельные изолированные именованные хранилища
volumes:
  catalog_data:
  order_data:
  rabbitmq_data:

networks:
  microservice-network:
    driver: bridge
